/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author caitl
 */
public class ResultTestGUI extends javax.swing.JFrame {

    /**
     * Creates new form ResultTestGUI
     */
    public ResultTestGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moduleNameLabel = new javax.swing.JLabel();
        cwContLabel = new javax.swing.JLabel();
        examContLabel = new javax.swing.JLabel();
        moduleNameTextField = new javax.swing.JTextField();
        cwContTextField = new javax.swing.JTextField();
        examContTextField = new javax.swing.JTextField();
        addModuleButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        bannerIdLabel = new javax.swing.JLabel();
        cwMarkLabel = new javax.swing.JLabel();
        examMarkLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        bannerIdTextField = new javax.swing.JTextField();
        cwMarkTextField = new javax.swing.JTextField();
        examMarkTextField = new javax.swing.JTextField();
        addStudentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        moduleDisplayTextArea = new javax.swing.JTextArea();
        quitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Result");

        moduleNameLabel.setText("Module Name");

        cwContLabel.setText("Coursework Contribution (%)");

        examContLabel.setText("Exam Contribution (%)");

        addModuleButton.setText("Add Module");
        addModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModuleButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Student Name");

        bannerIdLabel.setText("Banner ID");

        cwMarkLabel.setText("Coursework Mark");

        examMarkLabel.setText("Exam Mark");

        addStudentButton.setText("Add Student");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        moduleDisplayTextArea.setColumns(20);
        moduleDisplayTextArea.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        moduleDisplayTextArea.setRows(5);
        jScrollPane1.setViewportView(moduleDisplayTextArea);

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(examMarkLabel)
                                    .addComponent(cwMarkLabel)
                                    .addComponent(bannerIdLabel)
                                    .addComponent(nameLabel)
                                    .addComponent(moduleNameLabel)))
                            .addComponent(cwContLabel)
                            .addComponent(examContLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                                .addComponent(moduleNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bannerIdTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(examMarkTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                        .addComponent(cwMarkTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(cwContTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(examContTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(298, 298, 298)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addModuleButton)
                                    .addComponent(addStudentButton))))
                        .addGap(0, 270, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(quitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moduleNameLabel)
                    .addComponent(moduleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cwContLabel)
                    .addComponent(cwContTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examContLabel)
                    .addComponent(examContTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addModuleButton))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bannerIdLabel)
                    .addComponent(bannerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cwMarkLabel)
                    .addComponent(cwMarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentButton)
                    .addComponent(examMarkLabel)
                    .addComponent(examMarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(quitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModuleButtonActionPerformed
        // TODO add your handling code here:
        final int LIST_SIZE=30;
        this.studentList=new Module(LIST_SIZE, this.moduleNameTextField.getText(),
                       Integer.parseInt(this.cwContTextField.getText()), Integer.parseInt(this.examContTextField.getText()));
        this.addModuleButton.setVisible(false);
        this.moduleNameTextField.setEditable(false);
        this.cwContTextField.setEditable(false);
        this.examContTextField.setEditable(false);
        this.nameTextField.setEditable(true);
        this.bannerIdTextField.setEditable(true);
        this.cwMarkTextField.setEditable(true);
        this.examMarkTextField.setEditable(true);
        this.addStudentButton.setVisible(true);
    }//GEN-LAST:event_addModuleButtonActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        // TODO add your handling code here:
        this.studentList.addStudent(this.nameTextField.getText(), this.bannerIdTextField.getText(),
                        Integer.parseInt(this.cwMarkTextField.getText()), Integer.parseInt(this.examMarkTextField.getText()));
        this.moduleDisplayTextArea.setText(this.studentList.toString());
        this.nameTextField.setText("");
        this.bannerIdTextField.setText("");
        this.cwMarkTextField.setText("");
        this.examMarkTextField.setText("");
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResultTestGUI resultTest=new ResultTestGUI();
                resultTest.setVisible(true);
                resultTest.getNameTextField().setEditable(false);
                resultTest.getBannerIdTextField().setEditable(false);
                resultTest.getCwMarkTextField().setEditable(false);
                resultTest.getExamMarkTextField().setEditable(false);
                resultTest.getAddStudentButton().setVisible(false);
                resultTest.getModuleDisplayTextArea().setEditable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addModuleButton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JLabel bannerIdLabel;
    private javax.swing.JTextField bannerIdTextField;
    private javax.swing.JLabel cwContLabel;
    private javax.swing.JTextField cwContTextField;
    private javax.swing.JLabel cwMarkLabel;
    private javax.swing.JTextField cwMarkTextField;
    private javax.swing.JLabel examContLabel;
    private javax.swing.JTextField examContTextField;
    private javax.swing.JLabel examMarkLabel;
    private javax.swing.JTextField examMarkTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea moduleDisplayTextArea;
    private javax.swing.JLabel moduleNameLabel;
    private javax.swing.JTextField moduleNameTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables
private Module studentList;

public javax.swing.JTextField getNameTextField(){
    return this.nameTextField;
}

public javax.swing.JTextField getBannerIdTextField(){
    return this.bannerIdTextField;
}
 
public javax.swing.JTextField getCwMarkTextField(){
    return this.cwMarkTextField;
}

public javax.swing.JTextField getExamMarkTextField(){
    return this.examMarkTextField;
}

public javax.swing.JTextArea getModuleDisplayTextArea(){
    return this.moduleDisplayTextArea;
}

public javax.swing.JButton getAddStudentButton() {
    return this.addStudentButton;
}
}




